### ISSUE TITLE
1.14.4 NPE Crash with valid config

### ISSUE THREAD

**Issue by Partonetrain** [The-Fireplace-Minecraft-Mods/Block-Replacer#12]
Game crashes with valid config (NPE instead of "invalid config")

 * Forge 28.1.70
 * WGBR 2.1.1
* Other mods, but issue seems to be WGBR
 
Error (this is repeated for each chunk attempting to load):
`[11:30:43] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[11:30:44] [Server thread/ERROR]: Exception caught during firing event: null
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: class com.minecolonies.coremod.event.EventHandler onChunkLoad(Lnet/minecraftforge/event/world/ChunkEvent$Load;)V
		2: LOWEST
		3: ASM: class the_fireplace.wgblockreplacer.CommonEvents onEvent(Lnet/minecraftforge/event/world/ChunkEvent$Load;)V
java.lang.NullPointerException
	at the_fireplace.wgblockreplacer.CommonEvents.onEvent(CommonEvents.java:74)
	at net.minecraftforge.eventbus.ASMEventHandler_18_CommonEvents_onEvent_Load.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.world.server.ChunkManager.lambda$func_223172_f$14(ChunkManager.java:480)
	at net.minecraft.world.server.ChunkManager$$Lambda$6693/129275020.get(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:550)
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(SourceFile:273)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679)
	at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:452)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:81)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:94)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598)
	at java.lang.Thread.run(Thread.java:745)

[11:30:44] [Server thread/ERROR]: Couldn't load chunk [0, -10]
java.lang.NullPointerException: null
	at the_fireplace.wgblockreplacer.CommonEvents.onEvent(CommonEvents.java:74) ~[?:2.1.1]
	at net.minecraftforge.eventbus.ASMEventHandler_18_CommonEvents_onEvent_Load.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraft.world.server.ChunkManager.lambda$func_223172_f$14(ChunkManager.java:480) [?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$6693/129275020.get(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) [?:1.8.0_51]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:550) [?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(SourceFile:273) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:704) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679) [?:?]
	at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:452) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:81) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:94) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[11:30:44] [Server thread/ERROR]: Exception caught during firing event: null
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: class com.minecolonies.coremod.event.EventHandler onChunkLoad(Lnet/minecraftforge/event/world/ChunkEvent$Load;)V
		2: LOWEST
		3: ASM: class the_fireplace.wgblockreplacer.CommonEvents onEvent(Lnet/minecraftforge/event/world/ChunkEvent$Load;)V
java.lang.NullPointerException
	at the_fireplace.wgblockreplacer.CommonEvents.onEvent(CommonEvents.java:74)
	at net.minecraftforge.eventbus.ASMEventHandler_18_CommonEvents_onEvent_Load.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.world.server.ChunkManager.lambda$func_223172_f$14(ChunkManager.java:480)
	at net.minecraft.world.server.ChunkManager$$Lambda$6693/129275020.get(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:550)
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(SourceFile:273)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679)
	at net.minecraft.server.MinecraftServer.func_213186_a(MinecraftServer.java:452)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:81)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:94)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598)
	at java.lang.Thread.run(Thread.java:745)`

Full Log (too big for pastebin):
[latest.log](https://github.com/The-Fireplace-Minecraft-Mods/Block-Replacer/files/3800713/latest.log)

Config: 
https://pastebin.com/TxtPVfz9

**Comment by The-Fireplace** [comment]
I can _kind of_ work around this but it seems this is a Forge bug, and working around it would result in replacement being unreliable. I'll dig in a little more and see if I can get the root problem reported on Forge's issue tracker.

**Comment by The-Fireplace** [comment]
I've determined the cause to be MinecraftForge/MinecraftForge#6297
