### ISSUE TITLE
Game start crash.

### ISSUE THREAD

**Issue by samuelt005** [The-Fireplace-Minecraft-Mods/Block-Replacer#9]
I have crashes everytime a have the mod installed and configured. Sometimes it opens for just one time, after that when i try to enter the game again it simply crash.
Log: 
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.6.0-160-universal.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 7/19/19 12:24 PM
Description: Initializing game

java.lang.ClassCastException: zmaster587.advancedRocketry.armor.ItemSpaceArmor cannot be cast to net.dries007.tfc.api.capability.size.IItemSize
	at net.dries007.tfc.api.capability.size.CapabilityItemSize.getIItemSize(CapabilityItemSize.java:62)
	at net.dries007.tfc.client.ClientEvents.onItemTooltip(ClientEvents.java:214)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_40_ClientEvents_onItemTooltip_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.dries007.tfc.api.capability.size.CapabilityItemSize.getIItemSize(CapabilityItemSize.java:62)
	at net.dries007.tfc.client.ClientEvents.onItemTooltip(ClientEvents.java:214)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_40_ClientEvents_onItemTooltip_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at java.lang.Iterable.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1272332480 bytes (1213 MB) / 1983381504 bytes (1891 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                   | Source                                                    | Signature                                |
	|:----- |:-------------------- |:------------------------- |:--------------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                    | minecraft.jar                                             | None                                     |
	| LCH   | mcp                  | 9.42                      | minecraft.jar                                             | None                                     |
	| LCH   | FML                  | 8.0.99.99                 | forge-1.12.2-14.23.5.2838-universal.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2838              | forge-1.12.2-14.23.5.2838-universal.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | advancedrocketrycore | 1                         | minecraft.jar                                             | None                                     |
	| LCH   | libvulpes            | 0.4.1.-59                 | LibVulpes-1.12.2-0.4.1-59-universal.jar                   | None                                     |
	| LCH   | advancedrocketry     | 1.6.0.-160                | AdvancedRocketry-1.12.2-1.6.0-160-universal.jar           | None                                     |
	| LCH   | crafttweaker         | 4.1.19                    | CraftTweaker2-1.12-4.1.19.jar                             | None                                     |
	| LCH   | jei                  | 4.15.0.268                | jei_1.12.2-4.15.0.268.jar                                 | None                                     |
	| LCH   | mtlib                | 3.0.6                     | MTLib-3.0.6.jar                                           | None                                     |
	| LCH   | art                  | 1.0.0                     | ARTweaker-1.12.2-1.0.0.jar                                | None                                     |
	| LCH   | biomesoplenty        | 7.0.1.2439                | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar             | None                                     |
	| LCH   | ctgui                | 1.0.0                     | CraftTweaker2-1.12-4.1.19.jar                             | None                                     |
	| LCH   | crafttweakerjei      | 2.0.3                     | CraftTweaker2-1.12-4.1.19.jar                             | None                                     |
	| LCH   | journeymap           | 1.12.2-5.5.4              | journeymap-1.12.2-5.5.4.jar                               | None                                     |
	| LCH   | justenoughdimensions | 1.6.0-dev.20190711.220109 | justenoughdimensions-1.12.2-1.6.0-dev.20190711.220109.jar | 2b03e1423915a189b8094816baa18f239d576dff |
	| LCH   | resourceloader       | 1.5.3                     | ResourceLoader-MC1.12.1-1.5.3.jar                         | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | tellme               | 0.7.0-dev.20190610.165828 | tellme-1.12.2-0.7.0-dev.20190610.165828.jar               | 2b03e1423915a189b8094816baa18f239d576dff |
	| LCH   | tfc                  | ${version}                | TerraFirmaCraft-MC1.12.2-0.12.0.50.jar                    | None                                     |
	| LCH   | wgblockreplacer      | 2.0.3                     | WorldgenBlockReplacer-1.12.2-2.0.3.jar                    | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.6.0-160-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.86' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	TerraFirmaCraft: You are not running an official build. Please do not use this and then report bugs or issues.
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz`

**Comment by The-Fireplace** [comment]
Looks like an issue with TerraFirmaCraft. I suggest first trying an official build, since your log says `TerraFirmaCraft: You are not running an official build. Please do not use this and then report bugs or issues.`. Then, if you still have the issue, I recommend letting them know.
